### ISSUE TITLE
dfitpack.error

### ISSUE THREAD

**Issue by jwebster-LANL** [andersle/gpxplotter#22]
trying to plot a gpx file generated by a garmin GPSMAP 65s

I'm getting the error:

> Traceback (most recent call last):
>   File "gpxread.py", line 6, in <module>
>     for track in read_gpx_file('day1.gpx'):
>   File "C:\USERS\me\Anaconda3\envs\gpx\lib\site-packages\gpxplotter\gpxread.py", line 345, in read_gpx_file
>     process_segment(segment, max_heart_rate=max_heart_rate)
>   File "C:\USERS\me\Anaconda3\envs\gpx\lib\site-packages\gpxplotter\gpxread.py", line 286, in process_segment
>     segment['velocity'] = approximate_velocity(
>   File "C:\USERS\me\Anaconda3\envs\gpx\lib\site-packages\gpxplotter\gpxread.py", line 250, in approximate_velocity
>     spline = UnivariateSpline(time, distance, k=3)
>   File "C:\USERS\me\Anaconda3\envs\gpx\lib\site-packages\scipy\interpolate\fitpack2.py", line 202, in __init__
>     data = dfitpack.fpcurf0(x, y, k, w=w, xb=bbox[0],
> dfitpack.error: (m>k) failed for hidden m: fpcurf0:m=3

This is my code

```
from gpxplotter import read_gpx_file, create_folium_map, add_segment_to_map

my_map = create_folium_map(tiles='kartverket_topo4')
line_options = {'color': 'red', 'weight': 8, 'opacity': 0.5}

for track in read_gpx_file('day1.gpx'):
    for i, segment in enumerate(track['segments']):
        add_segment_to_map(my_map, segment) 
```

**Comment by andersle** [comment]
(Note to self - this is related to #21 #20 and the usage of [UnivariateSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html))

**Comment by andersle** [comment]
Hopefully, the latest version should now allow the code above to run without crashing.

**Comment by andersle** [comment]
Closed due to inactivity
